# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package definitions
COPY package.json package-lock.json ./

# Install dependencies without running prepare scripts
RUN npm ci --ignore-scripts

# Install TypeScript for build
RUN npm install typescript @types/node --no-save

# Copy source files and config
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npx tsc

# Default command to start the MCP server
CMD ["node", "build/index.js"]
